name: telnyx_flutter_webrtc
description: Telnyx's Dart and Flutter based WebRTC solution

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.22.3"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_messaging: ^15.1.6
  firebase_core: ^3.8.1
  flutter_callkit_incoming: ^2.0.4+1
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.0
  path_provider: ^2.1.5
  flutter_fgbg: ^0.6.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  telnyx_webrtc:
    path: ./packages/telnyx_webrtc


flutter:
  uses-material-design: true

  assets:
    - assets/audio/incoming_call.mp3
    - assets/audio/ringback_tone.mp3
    - assets/launcher.png
    - assets/images/
    - assets/icons/
