name: telnyx_webrtc
description: Enable real-time communication with WebRTC and Telnyx. Create and receive calls on Android, iOS and Web platforms
homepage: https://telnyx.com/
repository: https://github.com/team-telnyx/flutter-voice-sdk
issue_tracker: https://github.com/team-telnyx/flutter-voice-sdk/issues?q=is%3Aopen+is%3Aissue
version: 0.1.0

environment:
  sdk: ">=3.0.0 <3.22.3"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_webrtc: ^0.12.3
  logger: ^1.1.0
  uuid: ^3.0.6
  mockito: ^5.2.0
  build_runner: ^2.2.0
  audioplayers: ^5.2.1
  assets_audio_player: ^3.1.1
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter