name: telnyx_webrtc
description: Enable real-time communication with WebRTC and Telnyx. Create and receive calls on Android, iOS and Web platforms
homepage: https://telnyx.com/
repository: https://github.com/team-telnyx/flutter-voice-sdk
issue_tracker: https://github.com/team-telnyx/flutter-voice-sdk/issues
version: 1.0.0

environment:
  sdk: ">=3.0.0 <3.22.3"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.12.7
  logger: ^2.5.0
  uuid: ^4.5.1
  just_audio: ^0.9.43
  shared_preferences: ^2.4.0
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  build_runner: ^2.2.0
  flutter_lints: ^5.0.0
