// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE72LitYVx9o6O8zeOKEvB3Fy6txeKj00',
    appId: '1:884003177217:web:a718d5834c0cb9fa3b5100',
    messagingSenderId: '884003177217',
    projectId: 'fir-notification-test-1f87a',
    authDomain: 'fir-notification-test-1f87a.firebaseapp.com',
    storageBucket: 'fir-notification-test-1f87a.firebasestorage.app',
    measurementId: 'G-XJYJL7XJH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwqtp6y8hs45rxxStGStRb5rWjwDDBNGw',
    appId: '1:884003177217:android:bf1deaeb58b60c823b5100',
    messagingSenderId: '884003177217',
    projectId: 'fir-notification-test-1f87a',
    storageBucket: 'fir-notification-test-1f87a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYsBxsH_Lqkyd7vmELq6JJXuw1M78oE6g',
    appId: '1:884003177217:ios:d8ea4aa95607364d3b5100',
    messagingSenderId: '884003177217',
    projectId: 'fir-notification-test-1f87a',
    storageBucket: 'fir-notification-test-1f87a.firebasestorage.app',
    iosBundleId: 'com.telnyx.flutterWebrtc',
  );
}
