// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4AeOUpzZbqNPfT8S9t5oMxeTqV920ea0',
    appId: '1:1041583037627:web:a8b435ace03b9da5e19d9e',
    messagingSenderId: '1041583037627',
    projectId: 'traceit-ae280',
    authDomain: 'traceit-ae280.firebaseapp.com',
    databaseURL: 'https://traceit-ae280.firebaseio.com',
    storageBucket: 'traceit-ae280.appspot.com',
    measurementId: 'G-WMSQ66GN5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBvKRPAmK1AGqrhfN_3TalFnw-AKsof9M',
    appId: '1:1041583037627:android:398bfd2d3a70b324e19d9e',
    messagingSenderId: '1041583037627',
    projectId: 'traceit-ae280',
    databaseURL: 'https://traceit-ae280.firebaseio.com',
    storageBucket: 'traceit-ae280.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiCBmySlRCsQrNRT3HXpvgEyuYcefJd3k',
    appId: '1:1041583037627:ios:7d2f12363ba2e56ae19d9e',
    messagingSenderId: '1041583037627',
    projectId: 'traceit-ae280',
    databaseURL: 'https://traceit-ae280.firebaseio.com',
    storageBucket: 'traceit-ae280.appspot.com',
    androidClientId: '1041583037627-lchsc88avscqtq2if6lih4cihc7krle2.apps.googleusercontent.com',
    iosBundleId: 'com.telnyx.flutterWebrtc',
  );

}